### ISSUE TITLE
cpx: support DE2 campaign files

### ISSUE THREAD

**Issue by goto-bus-stop** [SiegeEngineers/genie-rs#20]
Need to figure out the format

**Comment by thowtue** [comment]
Hi !
Have you figured out the format of the Campaign files ?
Would be great if we can extract them :)

**Comment by goto-bus-stop** [comment]
I started doing something here https://github.com/SiegeEngineers/genie-rs/tree/de2-cpx but didn't get very far yet.

**Comment by goto-bus-stop** [comment]
Managed to find out just enough to be able to extract raw scenario files: https://github.com/SiegeEngineers/genie-rs/pull/22

**Comment by thowtue** [comment]
Allright !
Are DE2 campaign and scenario files that different from HD version ?

**Comment by goto-bus-stop** [comment]
They both contain a bunch of new bytes where I don't know what they are yet. It's hard to say exactly how different they are, even a small difference can cause parsers to fail in strange ways, sometimes at a totally different point. It just needs someone to look at it with a hex editor for a while :upside_down_face:

**Comment by thowtue** [comment]
Yes I see what you're talking about :')
There is no script nor software that compares HD and DE2 files and find the differences ? I mean with content extracted from hex edit soft

**Comment by thowtue** [comment]
Ok, I just figured out that I can extract scenarios from campaigns inside the DE2 editor. Just needed to copy the content of "..\Steam\steamapps\common\AoE2DE\resources\_common\campaign" to C:\Users\%userprofile%\Games\Age of Empires 2 DE\[USERID]\resources\_common\campaign
Then the game can red them. 
Like In HD I suppose, just never done that in HD so..

**Comment by goto-bus-stop** [comment]
Done by #22
